### ISSUE TITLE
Search as a fragment instead

### ISSUE THREAD

**Issue by CheezBoiger** [CS480-Spring2016-Android/TutorApp#1]
Not sure if you want to turn the Search feature into a fragment instead, or an activity.  Seems like there is both a fragment and activity for search, unless the profile Actvitiy is going to use the search fragment, grab the information searched, and display it on the Search Activity. I don't really know what you want to do here since the search activity is trying to access the search fragment's buttons and stuff heh 
this code in Search.java seems to be linked to activity_search.xml:

``` java
 @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_search);

```

But it is trying to access data from fragment_search.xml:

``` java
        Button searchBtn = (Button) findViewById(R.id.searchBtn);
        searchBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                search();
            }
        });
```

**Comment by CheezBoiger** [comment]
The slide menu i was able to get working for the Search Activity, but I came across this when i was debugging it, There were errors coming from here lulz.

**Comment by jacobromero** [comment]
Hmm no idea for fixes?
I'll try to look later, if you want to remove it and make a new one go for
it.

**Comment by CheezBoiger** [comment]
At the moment no, but I believe we can remove the searchBtn from the Search activity, or we may need to add another instance of a search button into the SearchActivity, that way it is not trying to access a fragment xml file.

**Comment by jacobromero** [comment]
Alright if you want to give that a shot

**Comment by CheezBoiger** [comment]
Alright, I got it to work with the slide menu. It's still an activity though, hopefully around the 3rd sprint we can just do some work to turn it into a fragment, but for now i should be fine for this sprint.

**Comment by CheezBoiger** [comment]
The search activity is being used, not the search fragment.

**Comment by CheezBoiger** [comment]
Also because we are using an activity on top of our profile activity, this may eat up battery life lulz... So turning it into a fragment will need to be something to do for optimization on our 3rd sprint.

**Comment by jacobromero** [comment]
Ok as long as it works for now lol

I'm going to try to clean up the profile screen in case we need to present
tomorrow

**Comment by CheezBoiger** [comment]
i hope not lol. At least we got something to show...

**Comment by CheezBoiger** [comment]
Alright, I'm closing this issue.
